<?php

/**
 * @var Magento\Customer\Block\Account\Customer $block
 */
?>
<div class="customer-menu-wrapper">
    <?php if ($block->customerLoggedIn()) : ?>
        <div class="actions dropdown options" role="link" tabindex="0" data-mage-init='{"dropdown":{}}' data-toggle="customer-menu" data-trigger-keypress-button="true" data-bind="scope: 'customer'">
            <button type="button" class="action showcustomer" tabindex="-1" data-action="customer-menu-toggle">
                <span class="action-label">
                    <?= $block->escapeHtml(__('Account')); ?>
                </span>
            </button>
        </div>
        <script type="text/x-magento-init">
            {
            "*": {
                "Magento_Ui/js/core/app": {
                    "components": {
                        "customer": {
                            "component": "Magento_Customer/js/view/customer"
                        }
                    }
                }
            }
        }
        </script>
    <?php else : ?>
        <a href="<?= $block->getBaseUrl() . 'customer/account/' ?>" class="action secondary showcustomer">
            <span class="action-label">
                <?= $block->escapeHtml(__('Login')); ?>
            </span>
        </a>
    <?php endif; ?>
    <?php if ($block->customerLoggedIn()) : ?>
        <?php if ($block->getChildHtml()) : ?>
            <div class="dropdown customer-menu" data-target="dropdown" role="dialog"><?= $block->getChildHtml() ?></div>
        <?php endif; ?>
    <?php endif; ?>
</div>
